export const GET_SIGNUP_INPUT = "GET_SIGNUP_INPUT";
export const IS_EMAIL_OTP_LOADING = "IS_EMAIL_OTP_LOADING";
export const EMAIL_OTP_CREATED = "EMAIL_OTP_CREATED";
export const IS_SIGNUP_LOADING = "IS_SIGNUP_LOADING";
export const IS_SIGNUP_COMPLETE = "IS_SIGNUP_COMPLETE";
export const IS_LOGIN_COMPLETE = "IS_LOGIN_COMPLETE";