import localFont from "next/font/local";
import "./globals.css";
import "./styles.css";
import 'font-awesome/css/font-awesome.css'



// import "../services/axios";
import { Providers } from "./Providers";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// console.log('12222222222', 12222222222)
export default function RootLayout({ children }) {
  return (<Providers>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        {children}


      </body>
    </html>
  </Providers>
  );
}
