import localFont from "next/font/local";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import '../../public/css/feather.css'
import '../../public/css/fontawesome/fontawesome.css'
import '../../public/css/select2.min.css'
import '../../public/css/splide.min.css'
import '../../public/css/main.css'

import { Providers } from "./Providers";
import BootstrapClient from "../../public/BootstrapClient";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html class="no-js" lang="zxx">
      <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>BootStrap HTML5 CSS3 Theme</title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="apple-touch-icon" href="apple-touch-icon.png" />
        <link rel="icon" href="images/favicon.png" type="image/x-icon" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <BootstrapClient /> {/* Load Bootstrap JS on the client */}
          {children}
        </Providers>
      </body>
    </html>

  );
}
